spring:
  application:
    name: backend

  # MySQL
  datasource:
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

#    hikari:
#      pool-name: HikariCP
#      maximum-pool-size: 5
#      connection-timeout: 10000
#      idle-timeout: 60000
#      max-lifetime: 1800000
#      leak-detection-threshold: 0
#      initialization-fail-timeout: -1

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081
